name: Auto Create Pull Request

on:
  push:
    # mainへの直接push以外、かつタグ以外のpushで起動
    branches-ignore:
      - main
    tags-ignore:
      - 'v*'

permissions:
  pull-requests: write
  contents: read

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 1. ブランチ名を取得 (例: issue-123/add-jump-sound)
          BRANCH_NAME="${{ github.ref_name }}"
          
          # 2. すでにPRが存在するか確認（二重作成防止）
          EXISTING_PR=$(gh pr list --head "$BRANCH_NAME" --json number --jq '.[0].number')
          if [ -n "$EXISTING_PR" ]; then
            echo "PR for $BRANCH_NAME already exists (#$EXISTING_PR). Skipping."
            exit 0
          fi

          # 3. ブランチ名からIssue番号を抽出 (issue-数字/ の形式を想定)
          # 正規表現で数字部分のみを抜き出す
          if [[ $BRANCH_NAME =~ ^issue-([0-9]+)/ ]]; then
            ISSUE_NUMBER="${BASH_REMATCH[1]}"
            BODY="fixes #$ISSUE_NUMBER"
            echo "Detected Issue Number: $ISSUE_NUMBER"
          else
            BODY="Created automatically by GitHub Actions."
            echo "No Issue number detected in branch name."
          fi

          # 4. PRの作成
          # タイトルはブランチ名そのまま。
          gh pr create \
            --title "$BRANCH_NAME" \
            --body "$BODY" \
            --base main \
            --head "$BRANCH_NAME"